name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest  

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2  

    - name: Set Up Python
      uses: actions/setup-python@v2  
      with:
        python-version: '3.9'  

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt 

    - name: Set Up MongoDB Environment Variables
      run: |
        echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" >> $GITHUB_ENV
        echo "MONGODB_USERNAME=${{ secrets.MONGODB_USERNAME }}" >> $GITHUB_ENV
        echo "MONGODB_PASSWORD=${{ secrets.MONGODB_PASSWORD }}" >> $GITHUB_ENV
      env:
        MONGODB_URI: ${{ secrets.MONGODB_URI }}
        MONGODB_USERNAME: ${{ secrets.MONGODB_USERNAME }}
        MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}

    - name: Run Tests
      run: |
        pytest tests/

    - name: Upload Test Results
      if: failure()  
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: ./test-results  

